### PR TITLE
load open api spec json file

### PR DESCRIPTION
**Pull request by francescorivola**

### CODE REVIEW

**Comment by francescorivola** [comment]
closes #5

**Comment by francescorivola** [comment]
@Juanjofp this PR is to add a basic mechanism to load the open api spec file and validate it using swagger-parser package.

**Review by Juanjofp — APPROVED** [review]
LGTM

**Review by Juanjofp — APPROVED** [review]
LGTM

**Comment by Juanjofp** [comment]
LGTM

**Pull request merged**
